return {
  ["workshop-1207269058"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-1418746242"]={
    ["configuration_options"]={
      ["clearfont"]=true,
      ["eventplus"]=true,
      ["extratrans"]=true,
      ["workshop-378160973"]=0 
    },
    ["enabled"]=true 
  },
  ["workshop-2321974509"]={ ["configuration_options"]={ ["SIB"]=false, ["SSB"]=false }, ["enabled"]=true },
  ["workshop-356420397"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-362175979"]={ ["configuration_options"]={ ["Draw over FoW"]="disabled" }, ["enabled"]=true },
  ["workshop-367546858"]={
    ["configuration_options"]={ ["LANG"]="auto", ["SMALL_TEXTURES"]=true },
    ["enabled"]=true 
  },
  ["workshop-380423963"]={
    ["configuration_options"]={
      [""]=0,
      ["boulder_blue"]=0.2,
      ["boulder_purple"]=0.05,
      ["change_cave_loot"]=false,
      ["common_loot_charcoal"]=0,
      ["common_loot_flint"]=0.35,
      ["common_loot_rocks"]=0.35,
      ["cutlichen"]=0,
      ["durian"]=0,
      ["flintless_blue"]=0.5,
      ["flintless_purple"]=0.1,
      ["flintless_red"]=0.2,
      ["foliage"]=0,
      ["gears"]=0,
      ["goldvein_purple"]=0.05,
      ["goldvein_red"]=0.1,
      ["guano"]=0,
      ["ice"]=0,
      ["lightbulb"]=0,
      ["moon_green"]=0.02,
      ["moon_orange"]=0.02,
      ["moon_yellow"]=0.02,
      ["pinecone"]=0,
      ["rare_loot_bluegem"]=0.015,
      ["rare_loot_marble"]=0.015,
      ["rare_loot_redgem"]=0.015,
      ["rottenegg"]=0,
      ["seeds"]=0,
      ["spoiled_food"]=0,
      ["stalagmite_green"]=0.02,
      ["stalagmite_orange"]=0.02,
      ["stalagmite_yellow"]=0.02,
      ["uncommon_loot_goldnugget"]=0.05,
      ["uncommon_loot_mole"]=0.05,
      ["uncommon_loot_nitre"]=0.05,
      ["uncommon_loot_rabbit"]=0.05 
    },
    ["enabled"]=true 
  },
  ["workshop-462434129"]={
    ["configuration_options"]={
      ["MOD_RESTART_ALLOW_KILL"]=true,
      ["MOD_RESTART_ALLOW_RESTART"]=true,
      ["MOD_RESTART_ALLOW_RESURRECT"]=true,
      ["MOD_RESTART_CD_BONUS"]=0,
      ["MOD_RESTART_CD_KILL"]=3,
      ["MOD_RESTART_CD_MAX"]=0,
      ["MOD_RESTART_CD_RESTART"]=3,
      ["MOD_RESTART_CD_RESURRECT"]=5,
      ["MOD_RESTART_FORCE_DROP_MODE"]=1,
      ["MOD_RESTART_IGNORING_ADMIN"]=true,
      ["MOD_RESTART_MAP_SAVE"]=1,
      ["MOD_RESTART_RESURRECT_HEALTH"]=100,
      ["MOD_RESTART_TRIGGER_MODE"]=1,
      ["MOD_RESTART_WELCOME_TIPS"]=true,
      ["MOD_RESTART_WELCOME_TIPS_TIME"]=6 
    },
    ["enabled"]=true 
  },
  ["workshop-569043634"]={
    ["configuration_options"]={
      ["Health_PenaHealth_Penalty_Meat_Effigylty_Portal"]="Unchanged",
      ["Health_Penalty_Generic"]="Unchanged",
      ["Health_Penalty_Maximum"]="Unchanged",
      ["Health_Penalty_Portal"]="Unchanged",
      ["Health_Respawn_Amount"]="Unchanged",
      ["campfire"]="Enabled",
      ["coldfire"]="Enabled",
      ["coldfirepit"]="Enabled",
      ["firepit"]="Enabled",
      ["reviver"]="Unchanged",
      ["skeleton"]="Unchanged",
      ["usetags"]="Unchanged" 
    },
    ["enabled"]=true 
  },
  ["workshop-661253977"]={
    ["configuration_options"]={
      ["amudiao"]=true,
      ["baodiao"]=0,
      ["kong"]=0,
      ["nillots"]=0,
      ["rendiao"]=0,
      ["zbdiao"]=true 
    },
    ["enabled"]=true 
  } 
}
